export type Service = {
  slug: string;
  title: string;
  vertical: "financial" | "real-estate" | "legal";
  tagline: string;
  description: string;
  whoIsItFor: string[];
  process: { step: number; title: string; description: string }[];
  benefits: string[];
  documentsRequired?: string[];
  faqs: { question: string; answer: string }[];
  relatedServices: string[];
  metaTitle: string;
  metaDescription: string;
};

// ─────────────────────────────────────────────
// FINANCIAL SERVICES (21 services)s
// ─────────────────────────────────────────────

const financialServices: Service[] = [
  {
    slug: "equity-commodity",
    title: "Equity & Commodity Market",
    vertical: "financial",
    tagline: "Expert guidance for stock market and commodity investments in Bangalore.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["mutual-funds", "portfolio-management", "financial-planning"],
    metaTitle: "Equity & Commodity Market Advisory in Bangalore | Right Asset Management",
    metaDescription: "Get expert equity and commodity market advisory services in Bangalore. SEBI-registered advisors to help you invest confidently.",
  },
  {
    slug: "mutual-funds",
    title: "Mutual Funds & SIP",
    vertical: "financial",
    tagline: "Grow your wealth systematically with expert mutual fund and SIP advisory.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["equity-commodity", "nps", "financial-planning"],
    metaTitle: "Mutual Fund & SIP Advisory in Bangalore | Right Asset Management",
    metaDescription: "Start your SIP or invest in mutual funds with expert guidance in Bangalore. Right Asset Management helps you choose the right funds for your goals.",
  },
  {
    slug: "health-insurance",
    title: "Health Insurance",
    vertical: "financial",
    tagline: "Protect your family with the right health insurance plan.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["life-insurance", "financial-planning", "mutual-funds"],
    metaTitle: "Health Insurance Advisory in Bangalore | Right Asset Management",
    metaDescription: "Find the best health insurance plan for you and your family in Bangalore. Compare plans and get expert advice from Right Asset Management.",
  },
  {
    slug: "life-insurance",
    title: "Life Insurance",
    vertical: "financial",
    tagline: "Secure your family's future with the right life insurance coverage.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["health-insurance", "financial-planning", "nps"],
    metaTitle: "Life Insurance Advisory in Bangalore | Right Asset Management",
    metaDescription: "Get the right life insurance plan to protect your family's financial future. Expert advisory from Right Asset Management in Bangalore.",
  },
  {
    slug: "home-loan",
    title: "Home Loans",
    vertical: "financial",
    tagline: "Get the best home loan rates with end-to-end assistance.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["personal-loan", "vehicle-loan", "financial-planning"],
    metaTitle: "Home Loan Advisory in Bangalore | Right Asset Management",
    metaDescription: "Get the best home loan deals in Bangalore. Right Asset Management helps you compare rates, prepare documents, and get approvals faster.",
  },
  {
    slug: "personal-loan",
    title: "Personal Loans",
    vertical: "financial",
    tagline: "Quick personal loan assistance with the best rates in Bangalore.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["home-loan", "vehicle-loan", "credit-score"],
    metaTitle: "Personal Loan Advisory in Bangalore | Right Asset Management",
    metaDescription: "Need a personal loan in Bangalore? Right Asset Management helps you get the best rates and fastest approvals across top banks and NBFCs.",
  },
  {
    slug: "vehicle-loan",
    title: "Vehicle Loans",
    vertical: "financial",
    tagline: "Drive your dream vehicle with hassle-free loan assistance.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["home-loan", "personal-loan", "credit-score"],
    metaTitle: "Vehicle Loan Advisory in Bangalore | Right Asset Management",
    metaDescription: "Get the best vehicle loan rates in Bangalore for car, bike, or commercial vehicles. Right Asset Management simplifies the entire loan process.",
  },
  {
    slug: "fixed-deposits",
    title: "Fixed Deposits",
    vertical: "financial",
    tagline: "Maximize your FD returns with expert guidance on the best schemes.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["bonds-ncd", "ppf", "mutual-funds"],
    metaTitle: "Fixed Deposit Advisory in Bangalore | Right Asset Management",
    metaDescription: "Get the best fixed deposit rates and expert FD advice in Bangalore. Right Asset Management helps you find safe, high-return FD options.",
  },
  {
    slug: "portfolio-management",
    title: "Portfolio Management Services",
    vertical: "financial",
    tagline: "Professional portfolio management for HNI investors in Bangalore.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["equity-commodity", "aif", "financial-planning"],
    metaTitle: "Portfolio Management Services in Bangalore | Right Asset Management",
    metaDescription: "Professional portfolio management for high-net-worth investors in Bangalore. SEBI-registered advisors managing your wealth end-to-end.",
  },
  {
    slug: "bonds-ncd",
    title: "Bonds & NCDs",
    vertical: "financial",
    tagline: "Invest in bonds and NCDs for stable, predictable returns.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["fixed-deposits", "aif", "portfolio-management"],
    metaTitle: "Bonds & NCD Investment Advisory in Bangalore | Right Asset Management",
    metaDescription: "Invest in government bonds and NCDs with expert guidance in Bangalore. Right Asset Management helps you build a stable fixed-income portfolio.",
  },
  {
    slug: "aif",
    title: "Alternate Investment Funds (AIF)",
    vertical: "financial",
    tagline: "Access exclusive AIF opportunities for sophisticated investors.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["portfolio-management", "bonds-ncd", "equity-commodity"],
    metaTitle: "Alternate Investment Funds (AIF) Advisory in Bangalore | Right Asset Management",
    metaDescription: "Invest in SEBI-regulated Alternate Investment Funds in Bangalore. Right Asset Management provides expert AIF advisory for accredited investors.",
  },
  {
    slug: "nps",
    title: "National Pension Scheme (NPS)",
    vertical: "financial",
    tagline: "Plan your retirement with NPS — tax-efficient and government-backed.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["ppf", "mutual-funds", "financial-planning"],
    metaTitle: "NPS Advisory in Bangalore | Right Asset Management",
    metaDescription: "Open your NPS account and plan for a secure retirement in Bangalore. Right Asset Management guides you through NPS enrollment and contributions.",
  },
  {
    slug: "ppf",
    title: "Public Provident Fund (PPF)",
    vertical: "financial",
    tagline: "Build a tax-free retirement corpus with PPF — safe and sovereign.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["nps", "sukanya-samriddhi", "fixed-deposits"],
    metaTitle: "PPF Advisory in Bangalore | Right Asset Management",
    metaDescription: "Open and manage your PPF account with expert guidance in Bangalore. Right Asset Management helps you maximize your PPF tax benefits and returns.",
  },
  {
    slug: "sukanya-samriddhi",
    title: "Sukanya Samriddhi Yojana",
    vertical: "financial",
    tagline: "Secure your daughter's future with the best girl-child savings scheme.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["ppf", "nps", "life-insurance"],
    metaTitle: "Sukanya Samriddhi Yojana Advisory in Bangalore | Right Asset Management",
    metaDescription: "Open a Sukanya Samriddhi account for your daughter in Bangalore. Right Asset Management guides you through the enrollment process and benefits.",
  },
  {
    slug: "atal-pension",
    title: "Atal Pension Yojana",
    vertical: "financial",
    tagline: "Guaranteed pension for a secure retirement — accessible to all.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["nps", "ppf", "financial-planning"],
    metaTitle: "Atal Pension Yojana Advisory in Bangalore | Right Asset Management",
    metaDescription: "Enroll in Atal Pension Yojana and secure a guaranteed monthly pension. Right Asset Management assists with APY enrollment in Bangalore.",
  },
  {
    slug: "gold-investment",
    title: "Gold Investment (SGB, ETF)",
    vertical: "financial",
    tagline: "Invest in gold smartly — Sovereign Gold Bonds and Gold ETFs.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["mutual-funds", "bonds-ncd", "portfolio-management"],
    metaTitle: "Gold Investment Advisory in Bangalore | Right Asset Management",
    metaDescription: "Invest in Sovereign Gold Bonds and Gold ETFs with expert guidance in Bangalore. Right Asset Management helps you add gold to your portfolio smartly.",
  },
  {
    slug: "startup-funding",
    title: "Startup Funding Advisory",
    vertical: "financial",
    tagline: "Navigate startup funding — angel, VC, and government grants advisory.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["financial-planning", "portfolio-management", "tax-planning"],
    metaTitle: "Startup Funding Advisory in Bangalore | Right Asset Management",
    metaDescription: "Get expert startup funding advisory in Bangalore. Right Asset Management helps startups connect with angels, VCs, and government grant programs.",
  },
  {
    slug: "tax-planning",
    title: "Tax Planning & ITR Filing",
    vertical: "financial",
    tagline: "Minimize your tax liability legally with expert planning and ITR filing.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["financial-planning", "ppf", "nps"],
    metaTitle: "Tax Planning & ITR Filing in Bangalore | Right Asset Management",
    metaDescription: "Expert tax planning and ITR filing services in Bangalore. Right Asset Management helps you save tax legally and file accurate returns on time.",
  },
  {
    slug: "credit-score",
    title: "Credit Score Improvement",
    vertical: "financial",
    tagline: "Improve your credit score to unlock better loan rates and higher limits.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["personal-loan", "home-loan", "financial-planning"],
    metaTitle: "Credit Score Improvement Services in Bangalore | Right Asset Management",
    metaDescription: "Struggling with a low credit score? Right Asset Management provides expert credit score improvement guidance in Bangalore to help you qualify for better loans.",
  },
  {
    slug: "financial-planning",
    title: "Comprehensive Financial Planning",
    vertical: "financial",
    tagline: "A complete financial plan built around your life goals and risk profile.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["mutual-funds", "tax-planning", "portfolio-management"],
    metaTitle: "Comprehensive Financial Planning in Bangalore | Right Asset Management",
    metaDescription: "Get a holistic financial plan tailored to your goals in Bangalore. Right Asset Management covers investments, insurance, tax, and retirement planning.",
  },
];

// ─────────────────────────────────────────────
// REAL ESTATE SERVICES (17 services)
// ─────────────────────────────────────────────

const realEstateServices: Service[] = [
  {
    slug: "buy-sell",
    title: "Buy & Sell Properties",
    vertical: "real-estate",
    tagline: "End-to-end property buying and selling assistance in Bangalore.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["property-registration", "sale-deed", "property-valuation"],
    metaTitle: "Buy & Sell Property in Bangalore | Right Asset Management",
    metaDescription: "Looking to buy or sell property in Bangalore? Right Asset Management provides end-to-end assistance from property search to registration.",
  },
  {
    slug: "sale-deed",
    title: "Sale Deed & Agreement to Sell",
    vertical: "real-estate",
    tagline: "Legally sound sale deed and agreement drafting by experienced professionals.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["buy-sell", "property-registration", "rent-agreement"],
    metaTitle: "Sale Deed & Agreement to Sell in Bangalore | Right Asset Management",
    metaDescription: "Get professionally drafted sale deeds and agreements to sell in Bangalore. Right Asset Management ensures legally compliant property documentation.",
  },
  {
    slug: "rent-agreement",
    title: "Rent Agreement",
    vertical: "real-estate",
    tagline: "Legally binding rent agreements drafted and registered quickly.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["sale-deed", "noc", "property-registration"],
    metaTitle: "Rent Agreement Services in Bangalore | Right Asset Management",
    metaDescription: "Get legally valid rent agreements drafted and registered in Bangalore. Right Asset Management handles the complete rental documentation process.",
  },
  {
    slug: "e-khatha",
    title: "E-Khatha Status & Application",
    vertical: "real-estate",
    tagline: "Get your E-Khatha certificate hassle-free in Bangalore.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["property-tax", "mutation", "property-registration"],
    metaTitle: "E-Khatha Application in Bangalore | Right Asset Management",
    metaDescription: "Apply for E-Khatha or check your E-Khatha status in Bangalore with expert help from Right Asset Management. Fast, accurate, and reliable service.",
  },
  {
    slug: "land-conversion",
    title: "Land Conversion (Agricultural → Residential)",
    vertical: "real-estate",
    tagline: "Convert agricultural land to residential use with expert guidance.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["building-plan", "e-khatha", "rtc-pahani"],
    metaTitle: "Land Conversion Services in Bangalore | Right Asset Management",
    metaDescription: "Convert agricultural land to residential or commercial use in Bangalore with expert assistance from Right Asset Management.",
  },
  {
    slug: "building-plan",
    title: "Building Plan Approval",
    vertical: "real-estate",
    tagline: "Navigate BBMP / BDA building plan approval with expert support.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["land-conversion", "e-khatha", "noc"],
    metaTitle: "Building Plan Approval in Bangalore | Right Asset Management",
    metaDescription: "Get your building plan approved by BBMP or BDA in Bangalore. Right Asset Management handles the complete approval process from start to finish.",
  },
  {
    slug: "encumbrance",
    title: "Encumbrance Certificate (EC)",
    vertical: "real-estate",
    tagline: "Obtain your EC quickly to verify clear property title.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["property-registration", "sale-deed", "buy-sell"],
    metaTitle: "Encumbrance Certificate (EC) in Bangalore | Right Asset Management",
    metaDescription: "Get your Encumbrance Certificate in Bangalore quickly. Right Asset Management helps verify clear property title through official EC extraction.",
  },
  {
    slug: "rtc-pahani",
    title: "RTC / Pahani Records",
    vertical: "real-estate",
    tagline: "Extract and verify RTC / Pahani land records in Karnataka.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["land-conversion", "mutation", "vamshavruksha"],
    metaTitle: "RTC / Pahani Records in Bangalore | Right Asset Management",
    metaDescription: "Extract RTC and Pahani land records in Karnataka with expert help. Right Asset Management verifies rural and urban land records accurately.",
  },
  {
    slug: "mutation",
    title: "Property Mutation",
    vertical: "real-estate",
    tagline: "Update ownership records after purchase or inheritance quickly.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["e-khatha", "property-registration", "rtc-pahani"],
    metaTitle: "Property Mutation Services in Bangalore | Right Asset Management",
    metaDescription: "Get property mutation done quickly in Bangalore after purchase or inheritance. Right Asset Management handles all khatha transfer formalities.",
  },
  {
    slug: "vamshavruksha",
    title: "Vamshavruksha (Family Tree Document)",
    vertical: "real-estate",
    tagline: "Get your Vamshavruksha for ancestral property and inheritance matters.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["rtc-pahani", "mutation", "property-registration"],
    metaTitle: "Vamshavruksha Document in Bangalore | Right Asset Management",
    metaDescription: "Obtain your Vamshavruksha family tree document in Bangalore for ancestral property claims. Right Asset Management assists with the complete process.",
  },
  {
    slug: "property-valuation",
    title: "Property Valuation",
    vertical: "real-estate",
    tagline: "Accurate property valuation for buying, selling, or loan purposes.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["buy-sell", "home-loan-property", "property-registration"],
    metaTitle: "Property Valuation Services in Bangalore | Right Asset Management",
    metaDescription: "Get accurate property valuation in Bangalore for buying, selling, loans, or legal purposes. Right Asset Management provides certified valuation reports.",
  },
  {
    slug: "property-tax",
    title: "Property Tax Services",
    vertical: "real-estate",
    tagline: "Pay and manage your BBMP property tax without the hassle.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["e-khatha", "mutation", "noc"],
    metaTitle: "Property Tax Services in Bangalore | Right Asset Management",
    metaDescription: "Get help with BBMP property tax payment, objections, and corrections in Bangalore. Right Asset Management simplifies property tax compliance.",
  },
  {
    slug: "noc",
    title: "NOC for Property",
    vertical: "real-estate",
    tagline: "Obtain No Objection Certificates for property transactions quickly.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["property-registration", "building-plan", "sale-deed"],
    metaTitle: "NOC for Property in Bangalore | Right Asset Management",
    metaDescription: "Get NOC certificates for property transactions in Bangalore. Right Asset Management handles NOC applications from all relevant authorities.",
  },
  {
    slug: "power-of-attorney",
    title: "Power of Attorney (Property)",
    vertical: "real-estate",
    tagline: "Draft and register property Power of Attorney with legal precision.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["sale-deed", "property-registration", "buy-sell"],
    metaTitle: "Power of Attorney for Property in Bangalore | Right Asset Management",
    metaDescription: "Get your property Power of Attorney drafted and registered in Bangalore. Right Asset Management ensures legally sound POA documentation.",
  },
  {
    slug: "joint-development",
    title: "Joint Development Agreement",
    vertical: "real-estate",
    tagline: "Expert JDA drafting and negotiation for landowners and builders.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["sale-deed", "property-registration", "power-of-attorney"],
    metaTitle: "Joint Development Agreement in Bangalore | Right Asset Management",
    metaDescription: "Get expert JDA drafting and negotiation services in Bangalore for landowners and developers. Right Asset Management ensures fair and legally sound agreements.",
  },
  {
    slug: "home-loan-property",
    title: "Home Loan Against Property",
    vertical: "real-estate",
    tagline: "Unlock the value in your property with a loan against property.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["property-valuation", "buy-sell", "encumbrance"],
    metaTitle: "Loan Against Property in Bangalore | Right Asset Management",
    metaDescription: "Get a loan against your property in Bangalore with the best rates. Right Asset Management helps you unlock liquidity from your real estate assets.",
  },
  {
    slug: "property-registration",
    title: "Property Registration Assistance",
    vertical: "real-estate",
    tagline: "Smooth, complete property registration support at the Sub-Registrar's office.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["sale-deed", "encumbrance", "mutation"],
    metaTitle: "Property Registration in Bangalore | Right Asset Management",
    metaDescription: "Get complete property registration assistance in Bangalore. Right Asset Management handles document preparation, stamp duty, and Sub-Registrar coordination.",
  },
];

// ─────────────────────────────────────────────
// LEGAL SERVICES (8 services)
// ─────────────────────────────────────────────

const legalServices: Service[] = [
  {
    slug: "property-disputes",
    title: "Property Disputes (Civil)",
    vertical: "legal",
    tagline: "Expert civil legal advisory for property boundary and title disputes.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["family-cases", "consumer-cases", "banking-cases"],
    metaTitle: "Property Dispute Lawyer in Bangalore | Right Asset Management",
    metaDescription: "Get expert legal advisory for property disputes in Bangalore. Right Asset Management connects you with experienced civil property lawyers.",
  },
  {
    slug: "criminal-advisory",
    title: "Criminal Case Advisory",
    vertical: "legal",
    tagline: "Experienced criminal case advisory to protect your rights.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["cyber-crime", "consumer-cases", "property-disputes"],
    metaTitle: "Criminal Case Advisory in Bangalore | Right Asset Management",
    metaDescription: "Get expert criminal case advisory in Bangalore. Right Asset Management helps you understand your rights and connects you with experienced criminal lawyers.",
  },
  {
    slug: "family-cases",
    title: "Family Case Support (Divorce, Maintenance)",
    vertical: "legal",
    tagline: "Sensitive, expert legal support for divorce, maintenance, and custody cases.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["property-disputes", "labour-cases", "consumer-cases"],
    metaTitle: "Family Case Legal Support in Bangalore | Right Asset Management",
    metaDescription: "Get sensitive and expert legal support for divorce, maintenance, and custody cases in Bangalore. Right Asset Management guides you through every step.",
  },
  {
    slug: "labour-cases",
    title: "Labour Case Help",
    vertical: "legal",
    tagline: "Protect your workplace rights with expert labour law advisory.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["family-cases", "consumer-cases", "banking-cases"],
    metaTitle: "Labour Case Advisory in Bangalore | Right Asset Management",
    metaDescription: "Get expert labour law advisory and case support in Bangalore. Right Asset Management helps employees and employers resolve workplace disputes legally.",
  },
  {
    slug: "insurance-claims",
    title: "Insurance Claim Cases",
    vertical: "legal",
    tagline: "Fight wrongful insurance claim rejections with expert legal support.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["consumer-cases", "banking-cases", "property-disputes"],
    metaTitle: "Insurance Claim Legal Advisory in Bangalore | Right Asset Management",
    metaDescription: "Get expert legal help for wrongfully rejected insurance claims in Bangalore. Right Asset Management helps you fight for the settlement you deserve.",
  },
  {
    slug: "banking-cases",
    title: "Banking & Financial Case Advisory",
    vertical: "legal",
    tagline: "Expert advisory for banking disputes, loan fraud, and financial case matters.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["consumer-cases", "insurance-claims", "cyber-crime"],
    metaTitle: "Banking Case Advisory in Bangalore | Right Asset Management",
    metaDescription: "Get expert legal advisory for banking disputes and financial cases in Bangalore. Right Asset Management helps with loan fraud, NPA notices, and recovery cases.",
  },
  {
    slug: "cyber-crime",
    title: "Cyber Crime Cases",
    vertical: "legal",
    tagline: "Report and fight cyber crime with expert legal guidance in Bangalore.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["criminal-advisory", "banking-cases", "consumer-cases"],
    metaTitle: "Cyber Crime Legal Advisory in Bangalore | Right Asset Management",
    metaDescription: "Get expert legal help for cyber crime cases in Bangalore — online fraud, identity theft, hacking, and more. Right Asset Management guides your complaint process.",
  },
  {
    slug: "consumer-cases",
    title: "Consumer Dispute Cases",
    vertical: "legal",
    tagline: "Fight unfair trade practices and defective products at the consumer forum.",
    description: "",
    whoIsItFor: [],
    process: [],
    benefits: [],
    documentsRequired: [],
    faqs: [],
    relatedServices: ["insurance-claims", "banking-cases", "labour-cases"],
    metaTitle: "Consumer Dispute Cases in Bangalore | Right Asset Management",
    metaDescription: "File consumer complaints and fight unfair trade practices in Bangalore. Right Asset Management provides expert consumer forum advisory.",
  },
];

// ─────────────────────────────────────────────
// COMBINED EXPORT
// ─────────────────────────────────────────────

export const allServices: Service[] = [
  ...financialServices,
  ...realEstateServices,
  ...legalServices,
];

export function getServiceBySlug(slug: string): Service | undefined {
  return allServices.find((s) => s.slug === slug);
}

export function getServicesByVertical(
  vertical: Service["vertical"]
): Service[] {
  return allServices.filter((s) => s.vertical === vertical);
}
